### ISSUE TITLE
Want to Catch an exception

### ISSUE THREAD

**Issue by zohaib-buyer** [influitive/apartment#184]
Hi,

I have add this (config.middleware.use 'Apartment::Elevators::Subdomain') in application.rb file.
When i try hit this in browser url 'test.domain.local:3000' where sub domain 'test' schema does not exist in PostgreSQL, i see this error 
Apartment::SchemaNotFound (One of the following schema(s) is invalid: test, "public")

I know is normal behavior of gem but want to catch this exception and redirect user to some other page, how can i do that?

**Comment by jurre** [comment]
@bradrobertson do you think it would make sense to allow for this to be configured? Maybe something like:

```ruby
# config/initializers/apartment.rb
Apartment.configure do |config|
  config.redirect_tenant_not_found_to "/"
end
```
And then handle this in the default middleware?

**Comment by bradrobertson** [comment]
I think it's better generally to hook into Rails whenever possible, so people can just use those mechanisms rather than requiring custom config options. Ideally I'd like to see something like:

```ruby
# application_controller.rb
class ApplicationController
  rescue_from Apartment::TenantNotFound do
    redirect_to root_path
  end
end
```

**Comment by jurre** [comment]
Yeah, I agree, but with the current middleware this never reaches rails and I don't think there's a clean way to get it there..

**Comment by bradrobertson** [comment]
I've definitely seen this work in other gems. If only I could remember *how*.

I'm going to take a stab at it today. There should be some what that Rails allows you to tap into their exception handling give you're injecting the middleware using their middleware injection mechanism rather than just Rack's.

**Comment by bradrobertson** [comment]
Ok so I can't really find anything to achieve what I wanted. We're going to improve on the docs for this, but really the best way is to implement your own custom middleware. We're updating the wiki/readme to have specific examples to achieve this. I'd rather than than muddy up the source with more config options.

Thanks for all the feedback.
