### ISSUE TITLE
Heroku and multi-tenant

### ISSUE THREAD

**Issue by comptasso** [influitive/apartment#209]
Heroku strongly advised against using multitenant apps. 
However I use it with now about 120 tenants for an accouting app but I'm afraid of potential difficulties if I ramp up to 1 thousand or event 10 thousands. 

Did you test a multitenant rails app on Heroku with a large number of tenants? 
What would be the best configuration to operate a large multitenant app ?

Sorry if it's not the right place for asking such a question.

**Comment by bradrobertson** [comment]
We only ever got up in the hundreds on Heroku before we switched off.

There are definitely downsides to scaling out thousands of tenants, but it really doesn't change whether you're on Heroku or not. At the end of the day it's just about your application structure, how much data you have, how many tables you have etc. There's no one recommended configuration really, but know that the more tables you have X the more schemas you have = the more objects in postgres that could potentially lead to slow downs.

**Comment by brancusi** [comment]
@bradrobertson what are some good alternatives to schema based multitenancy that would support smooth scaling? Is it realistic to cap each box at a certain number of tenants and then just load balance based on subdomain?

**Comment by bradrobertson** [comment]
I'm actively exploring sharding options. I *think* a sharding setup is available at a db level, so may not require any changes on Apartment itself, but not entirely sure. 

Another approach is the scoped based approach (ie just using foreign keys). I've been thinking about how this might fit into Apartment because I think the interface for switching tenants etc is really nice, but it would unfortunately however *likely* require some funky monkey patching on ActiveRecord.

As it stands there isn't really any hard limit. It's all dependent on the size of your machine. We have a db running with roughly 20GB of data and ~ 400 schemas and it all works fine. That's not huge or anything, but it's certainly not nothing.

**Comment by brancusi** [comment]
Thanks @bradrobertson. Makes sense. Definitely going to play around with it.

**Comment by bradrobertson** [comment]
I'm going to close this for now. It's definitely an idea that we want to explore with scoped based multi-tenancy, or the sharding option. I've actually talked with the guys that wrote pg_shard and [submitted a feature request](https://github.com/citusdata/pg_shard/issues/99) to allow sharding by `schema`. If you guys are particularly interested and want to add some `+1`'s to the ticket, I'm sure it would escalate the dev time. That would give us a true option to scale out schemas almost infinitely.
