### ISSUE TITLE
Foreign key issues with excluded models

### ISSUE THREAD

**Issue by stephenbaidu** [influitive/apartment#227]
Getting the below error with associated (belongs_to) models:

PG::ForeignKeyViolation: ERROR: insert or update on table "employees" violates foreign key constraint "fk_rails_0d62068e18" DETAIL: Key (contract_type_id)=(2) is not present in table "contract_types". : INSERT INTO "employees" ("title_id", "surname", "othernames", "department_id", "job_title_id", "gender_id", "date_of_birth", "contract_type_id", "employee_status_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING "id"

In this case, contract_type_id is a foreign_key to an excluded model (ContractType)

The error is reported to have come from this line:
@connection.exec_prepared(stmt_key, type_casted_binds.map { |_, val| val })

**Comment by bradrobertson** [comment]
Postgres doesn't really know about the multi-tenant setup and Apartment just copies all tables to all schemas, so it would likely assume to just look in the current schema's `contract_types` table for a record with `id=2` which obviously doesn't exist because it's in fact in the `public` schema.

This *might* be solved with a long standing issue of not having excluded tables in the tenanted schemas, but I haven't really come up with a solution to that (I'm not really actively working on it though)

**Comment by stephenbaidu** [comment]
Thank you. I have moved the excluded tables out and all works fine.
