### ISSUE TITLE
data migrations – migrate data using migrations

### ISSUE THREAD

**Issue by turboMaCk** [influitive/apartment#246]
Hi,
I have can't figure out how to write migration that include data changes in app using apartment. Basic migrations works as expected but when I try to use some model class in migration it fails. I already tried it using basic code like `User.find_each do..` or using [this gem](https://github.com/ka8725/migration_data).

here is exact migration that fails on `uninitialized constant` error:

```ruby
class RemoveVartiantAttrsFromProduct < ActiveRecord::Migration

  def change
    remove_column :products, :quantity, :integer, null: false, default: 0
    remove_column :products, :available, :boolean, null: false, default: false
    remove_column :products, :sku, :string
    remove_column :products, :ean, :string
    remove_column :products, :price, :decimal, null: false, default: 0.0
    remove_column :products, :supplier_key, :string

    #remove_index :products, column: :supplier_key
  end

  def data
    # Migrate non variant products to single variant
    Product.find_in_batches(:batch_size => 100) do |group|
      group.each do |p|
        if p.product_variants.length > 1
          ProductVarinat.create!(
            product: p,
            quantity: p.quantity,
            available: p.available,
            sku: p.sku,
            ean: p.ean,
            price: p.price,
            supplier_key: p.supplier_key
          )
        end
      end
    end
  end
end
```

**Comment by bradrobertson** [comment]
If you error is `Uninitialize constant "ProductVarinat"` it's because you spelled *Variant* wrong.

I can't really comment on Apartment working with the `migration_data` rubygem, but normal data migrations work as expected.

The way Apartment migrations work is by iterating over all tenants, switching into that tenant and running the migration, so if you're referencing a model in your migration, it will point to the currently migrated tenant. There's nothing special you need to do.

**Comment by turboMaCk** [comment]
@bradrobertson Awwww Sorry for that. My mistake. I was too much tired. The only problem was that typo.
