### ISSUE TITLE
Prefix newly created databases for tenants

### ISSUE THREAD

**Issue by firedev** [influitive/apartment#254]
Hi, I am using Apartment with MySQL and would like to have my databases prefixed with application database name, so say if my application is called `motivation` the tenant dbs should be `motivation_client1` and `motivation_client2`.

There is a setting in `config/initializers/apartment.rb`:   

```
# config.prepend_environment = !Rails.env.production?
```

I'd rather had something like `config.prepend_string = 'motivation'` for that matter. What is the general opinion on the subject? Thanks.

**Comment by bradrobertson** [comment]
Hmm... it's not a currently supported feature, but I could see the use case for wanting to munge the actual tenant name under the hood.

Instead of doing these one off `prepend_x` config options, we might be at the point where a full blown tenant name processor of some sort would work. We could write some default ones for the rails env prefix/suffix, but it could allow you to customize it yourself.

Maybe just something like:

```ruby
Apartment.configure do |config|
  config.tenant_name_processor = ->(tenant_name){ "motiviation_#{tenant_name}" }
```

I don't particularly love the `tenant_name_processor` as a feature name, but any thoughts?

**Comment by firedev** [comment]
Lambda sounds nice can't it be simply `config.tenant_name` though? Something like this:
```ruby
  config.tenant_names = -> { Company.pluck :subdomain }
  config.tenant_name = -> tenant_name { "motivation_#{tenant_name}" }
```

**Comment by bradrobertson** [comment]
Ya that makes sense.

Any chance you'd have time to PR this? It's not super high up on my list right now.

**Comment by firedev** [comment]
I'll see if it comes to this, got to wrap something first as well. Thanks for considering it anyway.
