### ISSUE TITLE
Why aren't databases recommended with PG?

### ISSUE THREAD

**Issue by emilebosch** [influitive/apartment#265]
The readme states that PG databases are not recommended. Why not?

**Comment by bradrobertson** [comment]
There's no benefit to it and it adds a bunch of maintenance overhead, plus it's [not widely used](http://www.poll-maker.com/results391552x4Bfb41a9-15#tab-2). 
We'll likely strip out connection based adapters to another gem in the future. 

I've never actually tested this, but I also suspect there would be a performance overhead to establishing a new connection on a per request basis, rather than just switching the `search_path` on the *same* connection.

**Comment by emilebosch** [comment]
Actually i tend to disagree, for enterprise setups:

- Having a separate database means separation of data. I.e. with an XSS hack one cannot easily access someone's other data using its injection vector.
- Having different backup schemes per apartment.

Have you considered this?

**Comment by bradrobertson** [comment]
1. I think you mean SQL injection attacks. Nothing about XSS would be more or less safe based on the choice of logical sharding you make, and if you're vulnerable to those then you've got more serious problems than the choice of tenancy that you use
2. In myself there's **literally** no difference between connection/non-connection adapters. In both cases, the underlying tenants still live on the same physical database machine. Apartment just issues a `use "tenant1"` command rather than establishing a new connection to a db on the same machine.
3. On postgresql we're using [postgresql schemas](http://www.postgresql.org/docs/9.4/static/ddl-schemas.html) which is another form of logical sharding that still keeps your data separate in much the same way mysql would through separate databases. Again if you're vulnerable to SQL injection, your tenanting strategy does NOT help you from a security perspective.
 
As for different backups schemes, no, I never considered that as I think you probably just want to back up all your data all the time :)

**Comment by emilebosch** [comment]
Sorry, i mean SQL injection attacks indeed. If the database strategy does indeed use "USE" then indeed it's useless. But when when its actually making a new connection to another database. Then i've im not mistaken you'd be safe, as long as you disallow use, you could Let's say an attacker after a login is able to do an SQL injection attack, then there is no way he could access another one's data if i'm correct.

You could use the subdomain as a user for instance. Am i missing something?

**Comment by bradrobertson** [comment]
Ya in that case you're correct, we just don't currently have the mechanism for `physical` sharding. Interestingly, I'm [currently chatting with someone else](https://github.com/influitive/apartment/issues/264) about a possible implementation for physical sharding using connections. May be what you're looking for?

**Comment by emilebosch** [comment]
Thanks! Ok, at least im not losing my mind Hahah. I'll check that out and if its the same. We'll head on the chat there! Thanks so much for building this!

**Comment by bradrobertson** [comment]
my pleasure!
