### ISSUE TITLE
Switch Tenant based on request.host

### ISSUE THREAD

**Issue by spq24** [influitive/apartment#280]
I am using a Apartment for a multi-tenant app. I recently realized I'll need to switch it to using the host instead of just the domain.

I saw the instructions for the HostHash elevator, but I'm really not sure how to use that. The example's are hard coded in there. How can I dynamically get the request.host if this code lives in an initializer (I have it in apartment.rb)?

I tried using: 

```
Rails.application.config.middleware.use 'Apartment::Elevators::HostHash', { request.host => request.host }

```

but when I do that I get undefined local variable or method 'request'. Same thing if I try Rack::Request.new(env) I get undefined local variable or method 'env' since it's in an initializer and doesn't have access to that.

How can I handle this?

Here's more on a SO question I asked if you need more context: http://stackoverflow.com/questions/33907927/request-host-in-initializer-rails-4

(btw it works if I hardcode one of my setup tenants, but this is obviously not a way I can handle this in a production app)

**Comment by bradrobertson** [comment]
I didn't write the [HostHash](https://github.com/influitive/apartment/blob/development/lib/apartment/elevators/host_hash.rb) middleware but I *believe* it's designed to be a fixed key/value pairing of hostname to tenant_name, so you'd use it like this:

```ruby
Rails.application.config.middleware.use 'Apartment::Elevators::HostHash', { "some.host" => "some_tenant }
```

It's not super useful TBH. It's failing for you though because you're trying to build a hash using variables that aren't in your scope.

If I were you i'd just write my own middleware using the [Generic Elevator](https://github.com/influitive/apartment/blob/development/lib/apartment/elevators/generic.rb). Something like:

```ruby
config.middleware.use 'Apartment::Elevators::Generic', ->(request) { SomeDataStore[request.host] }
```

Check out [the docs](https://github.com/influitive/apartment#switching-tenants-per-request) under "Custom Elevator"

**Comment by spq24** [comment]
Hey Brad,

Thanks I appreciate it. I'll work on a solution and if you're interested I can share what I come up with because I'm sure this could be useful to switch on full host. I'm in the process of switching over a legacy asp multi-tenant app that has 4 different base domains going to it and some duplicate subdomains so that was my use case.

**Comment by bradrobertson** [comment]
Sure you're welcome to share for other people, but I doubt we'd add that in as a feature. That's kind of the whole point of the generic elevator, to allow for your custom cases. That way we don't need to added all these esoteric use cases

**Comment by Xorelock** [comment]
I thought i'd chime in here because i'm currently evaluating this gem for similar purposes. I'm trying to support a multitenant environment where the customer will have their own vanity domain in some cases, and in others we will be providing them with a subdomain instead. Being able to switch on the full host is a valuable capability.

**Comment by sainejob** [comment]
We currently use this gem in production with the HostHash elevator -- we used to use the sub-domain elevator until we had a customer who wanted the custom domain

```
# initializer
Rails.application.config.middleware.use 'Apartment::Elevators::HostHash', Cloud.full_hosts_hash

# cloud.rb - Cloud Model
  def self.full_hosts_hash
    Cloud.all.inject(Hash.new) do |hash, cloud|
      hash[cloud.domain_name] = cloud.database_name # Cloud.database_name holds the tenant
      hash
    end
  end
```

We generate the Cloud/HostHash config on start and the `domain_name` holds 'tenant.mysaascompany.com' (these are subdomains) while those with customized domains have 'www.im-awesome.com'

**Comment by spq24** [comment]
Awesome! That worked perfectly for me.

**Comment by zenry** [comment]
I found extending the GenericElevator very easy

```
Rails.application.config.middleware.use 'SiteBake::SiteElevator'
```

```
require 'apartment/elevators/generic'

module SiteBake
  # SiteBake::SiteElevator
  class SiteElevator < Apartment::Elevators::Generic
    def parse_tenant_name(request)
      domain = Domain.find_by_host request.host

      return domain.site.token unless domain.nil?

      fail StandardError, "Domain with host #{request.host} not found"
    end
  end
end
```

**Comment by aakashbarot** [comment]
When I try to use with just host it is throwing error. 
When requiring 
`require 'apartment/elevators/host'`
It throw active support error of no such file found
`gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- apartment/elevators/host (LoadError)`

If I remove the require line it gives me name error on: 
`gems/apartment-1.2.0/lib/apartment/tenant.rb:73:in `const_missing': uninitialized constant Apartment::Elevators (NameError)`

It works with Subdomain, Domain, HostHash but not with Host. Any specific requirements or anything that I am missing out ? 

Thanks in advance .
