### ISSUE TITLE
Copy reference data from public tenant after new tenant creation?

### ISSUE THREAD

**Issue by wiiiim** [influitive/apartment#326]
Hello,

I have a public tenant with some reference data. Once a tenant is created this default reference data should be copied over into the new tenant (which they can then further customise later on).

I currently create the tenant after the creation of a Company (so each company ends up with its Postgres schema).
This is what I currently have. It doesn't seem to copy anything. I must be missing something. Are perhaps any of these apartment methods async?
Thanks

```
  Company.rb

  after_create :create_local_tenant

  def create_local_tenant
    Apartment::Tenant.create(self.domain)
    copy_reference_data(self.domain)
  end

  def copy_reference_data(tenant)
    # copy reference data from public tenant to new tenant, then switch back to current (admin) tenant
    current_tenant = Apartment::Tenant.current
    Apartment::Tenant.switch!('public')
    reference_data = ReferenceData.all
    Apartment::Tenant.switch!(tenant)
    reference_data.each{|rd| rd.dup.save}
    Apartment::Tenant.switch!(current_tenant)
  end
```

**Comment by bradrobertson** [comment]
Nothing is async no.

ActiveRecord relations aren't actually evaluated (ie queried from the db) until you go to iterate over them. So your lines:
```ruby
Apartment::Tenant.switch!('public')
reference_data = ReferenceData.all
```
Isn't actually pulling any data. The moment you call `reference_data.each{|rd| rd.dup.save}` the query is made, at which point you're on the new tenant you're trying to seed, so the query will yield an empty result, which aligns with your findings.

See [load](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-load) to force the query to happen.

Note you might want to put this in a background job rather than just an `after_create` as it could slow down your request to create companies significantly (not to mention your test suite).

**Comment by wiiiim** [comment]
thanks, thats very helpful!
speed is not too important here, companies/tenants are not created very often, and only by super admins

**Comment by bradrobertson** [comment]
just use `switch` with a block. It will automatically switch back after the block is done. I just realized this isn't documented. That'd probably help :p
