### ISSUE TITLE
web console (better_errors + binding_of_caller) uses public tenant with generic elevator

### ISSUE THREAD

**Issue by rvanlieshout** [influitive/apartment#349]
Issue #133 fixed a potential security risk, but also caused a web console to use the public tenant when something is raised.

Wouldn't it be better if we reset to public only if a tenant cannot be found? (thus not on any failure)

**Comment by rvanlieshout** [comment]
* Commit that changed this: cfe2bd9f7f29fcf52f0e81113ffa94ed51592dbc
* Switch back to public caused by: https://github.com/influitive/apartment/blob/development/lib/apartment/adapters/abstract_adapter.rb#L109

**Comment by typeoneerror** [comment]
@rvanlieshout  yo, so better_errors is provided as middleware, and I noticed recently that the rack stack order matters now with apartment because of the change you referenced. You need to insert apartment BEFORE better_errors to make sure the request is wrapped up in apartments switch context. 

Busy til sunday, but I mentioned to @bradrobertson that I'd submit a PR to note this in the documentation. I'd like to research how we could automatically insert the apartment middleware in the right place in certain contexts (Rails, Sinatra, et al) as well. We shall see.

**Comment by typeoneerror** [comment]
I do think switching the tenant back to public when the request is finished AND on errors is the right move, otherwise you risk "leaking the tenant into another request".  So we need to figure out the best way to insert the middleware in the proper location. Based on the default rails middleware stack (and what better_errors is doing), if Rails, we should insert it in a similar place (check out https://github.com/charliesome/better_errors/blob/f8aa9afebe559b1148bd30d5a152dafbdd87ac61/lib/better_errors/rails.rb#L12)

**Comment by typeoneerror** [comment]
Here's our middleware stack:

```
use Skylight::Middleware
use Rack::Cors
use ActionDispatch::SSL
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Raygun::Middleware::RackExceptionInterceptor
use Raygun::Middleware::RailsInsertAffectedUser
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use TenantDetectorMiddleware
use Warden::Manager
run App::Application.routes
```

This works with Devise because the TenantDetectorMiddleware (my Elevator is inserted before the Warden Manager. I'm thinking it might even work better to insert it before `use ActionDispatch::RemoteIp` and after `use ActionDispatch::DebugExceptions` based on what better_errors is doing. Thoughts? I feel like Cookies and Flash should be wrapped by the Elevator as well. @bradrobertson?

**Comment by rvanlieshout** [comment]
> I do think switching the tenant back to public when the request is finished AND on errors is the 
> right move, otherwise you risk "leaking the tenant into another request".

@typeoneerror, i fully agree with your statement on the current behavior and thank you for pointing me in this direction. It didn't even cross my mind.
