### ISSUE TITLE
Apartment and caches

### ISSUE THREAD

**Issue by jsperezg** [influitive/apartment#378]
Good morning all.

IMHO apartment should redefine the cache_key method for all models in tenants to something like this:

def cache_key
    "#{ self.class.name }/#{ Apartment::Tenant.current }/#{ self.id }-#{ self.updated_at.to_i }"
  end

**Comment by caironoleto** [comment]
You can avoid cache problems setting per tenant namespace. If you're using dalli as cache store, you can do this:

```ruby
config.cache_store = :dalli_store, 'cache-1.example.com', { :namespace => -> { Apartment::Tenant.current } }
```

**Comment by mikecmpbll** [comment]
the namespace option from @caironoleto looks like a great idea. i don't think we should override or force anything like this on users because a) might make it harder to have shared cache for certain things and b) we could cause people performance problems by adding a database query to every cache query.

i think this should be addressed in the readme though.

**Comment by jsperezg** [comment]
Thank you very much for your response! I'll adapt my code to work according to your suggestions!
