### ISSUE TITLE
PG::InFailedSqlTransaction on creating initial tenant

### ISSUE THREAD

**Issue by andymeneely** [influitive/apartment#404]
I've been having trouble converting my Rails 5 app to multi-tenant. I documented it on this [StackOverflow question](http://stackoverflow.com/questions/42445528/pginfailedsqltransaction-on-creating-initial-tenant).

Any help would be appreciated.

**Comment by andymeneely** [comment]
An update from the StackOverflow question [this answer](http://stackoverflow.com/a/42504877/1325339) mentioned that the `ar_internal_metadata` is a new table in Rails. Does Apartment now create it too with Rails 5?

Looks like there's some support in this commit: https://github.com/influitive/apartment/commit/bd3f56de3d5842ba333fa82f2dab9e65b7ec5592

**Comment by mikecmpbll** [comment]
something's failed during tenant create (to do with the "ar_internal_metadata" table), and apartment has tried to reset the tenant (set schema search path) but that is causing a secondary PG::InFailedSqlTransaction error relating to transactions.

the "ar_internal_metadata" table should be created when your db/schema.rb is loaded and it calls the `ActiveRecord::Schema.define` at the top; https://github.com/rails/rails/blob/master/activerecord/lib/active_record/schema.rb#L50-L56 .

i believe this is broken in with apartment and rails 5 due to the same issue here: #345 

i'm going to work on a fix asap :+1:

**Comment by mikecmpbll** [comment]
should be sorted in rails 5.1 ..

**Comment by anandshri** [comment]
@andymeneely I am facing the same issue. what is the solution ?

**Comment by andymeneely** [comment]
I actually put this part down on my project and I'll be revisiting it in a month or two - so I don't have one :(

**Comment by mikecmpbll** [comment]
@anandshri what version of rails? the rails team merged into 5-0-stable and 5-1-stable i believe so should be in patch releases for both. https://github.com/rails/rails/pull/28399

i'd try upgrade rails.

**Comment by telmogh** [comment]
I've upgraded Rails to `5.1.4`, and I'm still seeing this error.

**Comment by telmogh** [comment]
Ok, I guess it was just waiting for me to comment here. It's working now.

Btw, I've done `rake db:drop` + `rake db:create` + `rake db:migrate`
