### ISSUE TITLE
`quietly` not defined

### ISSUE THREAD

**Issue by cjbottaro** [influitive/apartment#424]
It's called as part of the `create` task:
```ruby
  desc "Create all tenants"
  task create: 'db:migrate' do
    tenants.each do |tenant|
      begin
        puts("Creating #{tenant} tenant")
        quietly { Apartment::Tenant.create(tenant) }
      rescue Apartment::TenantExists => e
        puts e.message
      end
    end
  end
```

On a side note, why does `create` rely on `migrate`?  How can something be migrated before it's created?

**Comment by mikecmpbll** [comment]
ha .. was introduced in #55, looks like a copy-paste mistake from when the tasks used to depend on their rails equivalents (should have been db:create), instead of enhace them as they do now. i assume it wasn't subsequently removed because it was assumed to be deliberate.

regards `quietly`, i merged #403 a while back but somehow i merged into wrong branch 😓 . i'll sort later.
