### ISSUE TITLE
While creating new tenant: PG::ActiveSqlTransaction: ERROR:  CREATE DATABASE cannot run inside a transaction block

### ISSUE THREAD

**Issue by masscrx** [influitive/apartment#433]
Hi,
When Im trying to create new tenant by model callback:
```
class Service < ActiveRecord::Base
  before_create :create_tenant
  private  	
    def create_tenant
      Apartment::Tenant.create(self.db_name)
    end
end
```
Im getting error: 
```
(0.9ms)  CREATE DATABASE "db_test1" ENCODING = 'utf8'
PG::ActiveSqlTransaction: ERROR:  CREATE DATABASE cannot run inside a transaction block : CREATE DATABASE "db_test1" ENCODING = 'utf8'
(0.3ms)  ROLLBACK
Completed 500 Internal Server Error in 119ms (ActiveRecord: 18.8ms)

Apartment::TenantExists (Error while creating tenant db_test1: PG::ActiveSqlTransaction: ERROR:  CREATE DATABASE cannot run inside a transaction block
: CREATE DATABASE "db_test1" ENCODING = 'utf8'):
```
**BUT**
While trying to create tenant on rails console - everything is fine.

**Comment by ocha** [comment]
@masscrx you need to disable transactions within your migration. Add following code inside your migration class (not method) `self.disable_ddl_transaction!`

**Comment by mikecmpbll** [comment]
ah yes. the problem is that activerecord callbacks run in a transaction but PG doesn't allow you to call `CREATE DATABASE` in a transaction. i don't have much PG experience but maybe @ocha's solution will work. alternatively, do it in another thread possibly, or use activejob to do the tenant creation in the background.

as this doens't seem much like an apartment issue, i'll close for now but let me know if there's a good solution and we can add it to readme if it's a common stumbling block.
