### ISSUE TITLE
excluded_subdomains doesn't seems to be working

### ISSUE THREAD

**Issue by tauqeer-ahmad** [influitive/apartment#456]
# config/initializers/apartment/subdomain_exclusions.rb
`Apartment::Elevators::Subdomain.excluded_subdomains = ['www']`

Above doesn't seems to be working. I'm using rails 5.0.2.

in apartment.rb I have this 
`Apartment::Elevators::Subdomain.excluded_subdomains = ['www', 'admin']
Rails.application.config.middleware.use 'Apartment::Elevators::Subdomain' `

To test on local i have added hosts
`127.0.0.1 www.example.com admin.example.com`

on www.example.com I got error `Apartment::TenantNotFound`
What I'm missing here.

**Comment by meganemura** [comment]
I could not reproduce this with Rails 5.0.2 + MySQL 5.7 + apartment 1.2.0 (latest release).
Would you tell us what database (and its version) are you using?

**Comment by tauqeer-ahmad** [comment]
'rails', '~> 5.0.2'
pg (0.20.0)
apartment (1.2.0)

**Comment by meganemura** [comment]
@tauqeer-ahmad 
thanks for the information.
And what is the version of PostgreSQL, not pg gem. Such as 9.3, 9.4, ..., 9.7.

Please execute `SELECT version();` query to the server, and tell us that.

**Comment by tauqeer-ahmad** [comment]
(PostgreSQL) 9.6.2

**Comment by meganemura** [comment]
@tauqeer-ahmad 

I could not reproduce this in the [dummy app I created](https://github.com/meganemura/apartment-apps/tree/master/issue456).
You said you got `Apartment::TenantNotFound` on `www.example.com`.
But this app can be successfly accessed for http://www.lvh.me:3000.
(additional note: [lvh.me](https://coderwall.com/p/-neplg/use-lvh-me-for-local-subdomain-testing) might be useful for you. )

In addition, the app cannot be accessed for http://admin.lvh.me:3000/.
`admin.lvh.me` tells us `Apartment::TenantNotFound` just like you described.
This is because that `Apartment::Elevators::Subdomain.excluded_subdomains` is defined in `config/initializers/apartment.rb` first as `['www', 'admin']`, and is overridden in `config/initializers/apartment/subdomain_exclusions.rb` finally as `['www']`.

Would you confirm what is the difference between your app's configurations and my dummy app's.
